{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5837d612-c2cd-4a9b-9cc5-7510f588917e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-04-17 13:44:17.087 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-04-17 13:44:17.092 No runtime found, using MemoryCacheStorageManager\n",
      "2026-04-17 13:44:17.100 No runtime found, using MemoryCacheStorageManager\n",
      "2026-04-17 13:44:27.843 Session state does not function when running a script without `streamlit run`\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "Capstone 2 — Supply Chain Analytics & Revenue Forecasting\n",
    "Streamlit Web App | app.py\n",
    "Author: Atharva\n",
    "\"\"\"\n",
    "\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.graph_objects as go\n",
    "import plotly.express as px\n",
    "from plotly.subplots import make_subplots\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# ── PAGE CONFIG ────────────────────────────────────────────────────────────\n",
    "st.set_page_config(\n",
    "    page_title=\"Supply Chain Analytics\",\n",
    "    page_icon=\"📦\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\"\n",
    ")\n",
    "\n",
    "# ── CUSTOM CSS ─────────────────────────────────────────────────────────────\n",
    "st.markdown(\"\"\"\n",
    "<style>\n",
    "    .metric-card {\n",
    "        background: linear-gradient(135deg, #1F4E79 0%, #2E75B6 100%);\n",
    "        border-radius: 12px;\n",
    "        padding: 20px;\n",
    "        color: white;\n",
    "        text-align: center;\n",
    "        margin-bottom: 10px;\n",
    "    }\n",
    "    .metric-card .value { font-size: 28px; font-weight: 700; }\n",
    "    .metric-card .label { font-size: 13px; opacity: 0.85; margin-top: 4px; }\n",
    "    .section-header {\n",
    "        background: #EBF3FB;\n",
    "        border-left: 4px solid #2E75B6;\n",
    "        padding: 8px 16px;\n",
    "        border-radius: 0 8px 8px 0;\n",
    "        font-weight: 600;\n",
    "        color: #1F4E79;\n",
    "        margin-bottom: 16px;\n",
    "    }\n",
    "    .stMetric { background: #F5F9FD; border-radius: 8px; padding: 12px; }\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# ── DATA LOADERS ───────────────────────────────────────────────────────────\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    master     = pd.read_csv('master_dataset.csv')\n",
    "    monthly    = pd.read_csv('monthly_revenue.csv')\n",
    "    forecast   = pd.read_csv('forecast_next12months.csv')\n",
    "    evaluation = pd.read_csv('forecast_evaluation.csv')\n",
    "    metrics    = pd.read_csv('model_metrics.csv')\n",
    "\n",
    "    master['order_purchase_timestamp'] = pd.to_datetime(master['order_purchase_timestamp'], errors='coerce')\n",
    "    monthly['ds']    = pd.to_datetime(monthly['ds'])\n",
    "    forecast['ds']   = pd.to_datetime(forecast['ds'])\n",
    "    evaluation['ds'] = pd.to_datetime(evaluation['ds'])\n",
    "\n",
    "    return master, monthly, forecast, evaluation, metrics\n",
    "\n",
    "# Load with spinner on first run\n",
    "with st.spinner(\"Loading data...\"):\n",
    "    try:\n",
    "        master, monthly, forecast, evaluation, metrics = load_data()\n",
    "        data_loaded = True\n",
    "    except Exception as e:\n",
    "        data_loaded = False\n",
    "        st.error(f\"Could not load data files: {e}\\nMake sure all CSV files are in the same folder as app.py\")\n",
    "\n",
    "# ── SIDEBAR ────────────────────────────────────────────────────────────────\n",
    "st.sidebar.image(\"https://img.icons8.com/color/96/000000/delivery.png\", width=80)\n",
    "st.sidebar.title(\"📦 Supply Chain Analytics\")\n",
    "st.sidebar.markdown(\"---\")\n",
    "\n",
    "page = st.sidebar.radio(\n",
    "    \"Navigate\",\n",
    "    [\"🏠 Overview\",\n",
    "     \"📈 Revenue Forecast\",\n",
    "     \"🔍 EDA — Trends\",\n",
    "     \"🏷️ EDA — Categories\",\n",
    "     \"🗺️ EDA — Geography\",\n",
    "     \"🚚 EDA — Delivery\",\n",
    "     \"🤖 Model Metrics\"]\n",
    ")\n",
    "\n",
    "st.sidebar.markdown(\"---\")\n",
    "if data_loaded:\n",
    "    st.sidebar.success(f\"✅ Data loaded\\n{master.shape[0]:,} records\")\n",
    "st.sidebar.markdown(\"**Model:** Facebook Prophet\")\n",
    "st.sidebar.markdown(\"**Forecast:** Next 12 months\")\n",
    "st.sidebar.markdown(\"---\")\n",
    "st.sidebar.caption(\"Capstone Project 2 | Atharva\")\n",
    "\n",
    "if not data_loaded:\n",
    "    st.stop()\n",
    "\n",
    "# ── HELPERS ────────────────────────────────────────────────────────────────\n",
    "delivered = master[master['order_status'] == 'delivered'].copy()\n",
    "\n",
    "def card(label, value):\n",
    "    return f\"\"\"\n",
    "    <div class=\"metric-card\">\n",
    "        <div class=\"value\">{value}</div>\n",
    "        <div class=\"label\">{label}</div>\n",
    "    </div>\"\"\"\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "# PAGE 1 — OVERVIEW\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "if page == \"🏠 Overview\":\n",
    "    st.title(\"🏠 Supply Chain Dashboard — Overview\")\n",
    "    st.markdown(\"**Brazilian E-Commerce Analytics | 2016–2026**\")\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    # KPI Row\n",
    "    col1, col2, col3, col4 = st.columns(4)\n",
    "    with col1:\n",
    "        st.metric(\"Total Orders\", f\"{master['order_id'].nunique():,}\")\n",
    "    with col2:\n",
    "        st.metric(\"Total Revenue\", f\"R${delivered['item_revenue'].sum()/1e6:.1f}M\")\n",
    "    with col3:\n",
    "        st.metric(\"Avg Order Value\", f\"R${delivered['item_revenue'].mean():,.0f}\")\n",
    "    with col4:\n",
    "        st.metric(\"On-Time Rate\", f\"{delivered['on_time_delivery'].mean()*100:.1f}%\")\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    col1, col2, col3, col4 = st.columns(4)\n",
    "    with col1:\n",
    "        st.metric(\"Total Customers\", f\"{master['customer_id'].nunique():,}\")\n",
    "    with col2:\n",
    "        st.metric(\"Avg Delivery Days\", f\"{delivered['delivery_days'].mean():.1f}\")\n",
    "    with col3:\n",
    "        total_cats = master['product_category_name'].nunique()\n",
    "        st.metric(\"Product Categories\", f\"{total_cats}\")\n",
    "    with col4:\n",
    "        cancel_pct = (master['order_status'] == 'canceled').mean() * 100\n",
    "        st.metric(\"Cancellation Rate\", f\"{cancel_pct:.1f}%\")\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "    st.subheader(\"📅 Monthly Revenue Overview\")\n",
    "    fig = go.Figure()\n",
    "    fig.add_trace(go.Scatter(\n",
    "        x=monthly['ds'], y=monthly['y'],\n",
    "        fill='tozeroy', fillcolor='rgba(46, 117, 182, 0.15)',\n",
    "        line=dict(color='#2E75B6', width=2),\n",
    "        name='Monthly Revenue'\n",
    "    ))\n",
    "    fig.update_layout(\n",
    "        height=350,\n",
    "        xaxis_title=\"Date\", yaxis_title=\"Revenue (R$)\",\n",
    "        yaxis_tickformat='R$,.0f',\n",
    "        margin=dict(l=20, r=20, t=20, b=20),\n",
    "        hovermode='x unified'\n",
    "    )\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    col1, col2 = st.columns(2)\n",
    "    with col1:\n",
    "        st.subheader(\"📊 Order Status\")\n",
    "        status_counts = master['order_status'].value_counts()\n",
    "        fig2 = px.pie(values=status_counts.values, names=status_counts.index,\n",
    "                      color_discrete_sequence=px.colors.qualitative.Set2)\n",
    "        fig2.update_layout(height=300, margin=dict(l=0, r=0, t=20, b=0))\n",
    "        st.plotly_chart(fig2, use_container_width=True)\n",
    "\n",
    "    with col2:\n",
    "        st.subheader(\"💳 Payment Types\")\n",
    "        pay_counts = master['payment_type'].value_counts()\n",
    "        fig3 = px.bar(x=pay_counts.values, y=pay_counts.index, orientation='h',\n",
    "                      color_discrete_sequence=['#2E75B6'])\n",
    "        fig3.update_layout(height=300, margin=dict(l=0, r=20, t=20, b=0),\n",
    "                            xaxis_title=\"Orders\", yaxis_title=\"\")\n",
    "        st.plotly_chart(fig3, use_container_width=True)\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "# PAGE 2 — REVENUE FORECAST\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "elif page == \"📈 Revenue Forecast\":\n",
    "    st.title(\"📈 Revenue Forecast — Next 12 Months\")\n",
    "    st.markdown(\"*Forecast generated using Facebook Prophet with Brazilian holiday calendar*\")\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    # Forecast metrics\n",
    "    col1, col2, col3 = st.columns(3)\n",
    "    with col1:\n",
    "        st.metric(\"Total Predicted Revenue\", f\"R${forecast['yhat'].sum()/1e6:.2f}M\")\n",
    "    with col2:\n",
    "        st.metric(\"Peak Month\", forecast.loc[forecast['yhat'].idxmax(), 'ds'].strftime('%B %Y'))\n",
    "    with col3:\n",
    "        avg_ci = ((forecast['yhat_upper'] - forecast['yhat_lower']) / forecast['yhat']).mean() * 100\n",
    "        st.metric(\"Avg Uncertainty Range\", f\"±{avg_ci:.1f}%\")\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    # Full history + forecast\n",
    "    st.subheader(\"📊 Historical Revenue + 12-Month Forecast\")\n",
    "    fig = go.Figure()\n",
    "\n",
    "    # Historical\n",
    "    fig.add_trace(go.Scatter(\n",
    "        x=monthly['ds'], y=monthly['y'],\n",
    "        name='Actual Revenue',\n",
    "        line=dict(color='#2E75B6', width=2),\n",
    "        mode='lines'\n",
    "    ))\n",
    "\n",
    "    # Confidence band\n",
    "    fig.add_trace(go.Scatter(\n",
    "        x=pd.concat([forecast['ds'], forecast['ds'][::-1]]),\n",
    "        y=pd.concat([forecast['yhat_upper'], forecast['yhat_lower'][::-1]]),\n",
    "        fill='toself', fillcolor='rgba(220, 38, 38, 0.15)',\n",
    "        line=dict(color='rgba(255,255,255,0)'),\n",
    "        name='95% Confidence Band'\n",
    "    ))\n",
    "\n",
    "    # Forecast line\n",
    "    fig.add_trace(go.Scatter(\n",
    "        x=forecast['ds'], y=forecast['yhat'],\n",
    "        name='Forecast',\n",
    "        line=dict(color='#DC2626', width=2.5, dash='dash'),\n",
    "        mode='lines+markers', marker=dict(size=6)\n",
    "    ))\n",
    "\n",
    "    fig.add_vline(x=monthly['ds'].max(), line_dash=\"dot\", line_color=\"gray\",\n",
    "                  annotation_text=\"Forecast start\", annotation_position=\"top right\")\n",
    "\n",
    "    fig.update_layout(\n",
    "        height=450,\n",
    "        xaxis_title=\"Date\", yaxis_title=\"Revenue (R$)\",\n",
    "        yaxis_tickformat='R$,.0f',\n",
    "        legend=dict(orientation=\"h\", y=1.02, x=0),\n",
    "        hovermode='x unified'\n",
    "    )\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    # Monthly bar chart\n",
    "    st.subheader(\"📅 Month-by-Month Forecast\")\n",
    "    forecast_display = forecast.copy()\n",
    "    forecast_display['month_label'] = forecast_display['ds'].dt.strftime('%b %Y')\n",
    "\n",
    "    fig2 = go.Figure()\n",
    "    fig2.add_trace(go.Bar(\n",
    "        x=forecast_display['month_label'],\n",
    "        y=forecast_display['yhat'],\n",
    "        name='Predicted Revenue',\n",
    "        marker_color='#2E75B6',\n",
    "        error_y=dict(\n",
    "            type='data', symmetric=False,\n",
    "            array=forecast_display['yhat_upper'] - forecast_display['yhat'],\n",
    "            arrayminus=forecast_display['yhat'] - forecast_display['yhat_lower'],\n",
    "            color='#555555'\n",
    "        )\n",
    "    ))\n",
    "    fig2.update_layout(\n",
    "        height=380, xaxis_title=\"Month\", yaxis_title=\"Predicted Revenue (R$)\",\n",
    "        yaxis_tickformat='R$,.0f'\n",
    "    )\n",
    "    st.plotly_chart(fig2, use_container_width=True)\n",
    "\n",
    "    # Table\n",
    "    st.subheader(\"📋 Forecast Table\")\n",
    "    forecast_table = forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].copy()\n",
    "    forecast_table.columns = ['Month', 'Predicted Revenue', 'Lower Bound (95%)', 'Upper Bound (95%)']\n",
    "    forecast_table['Month'] = forecast_table['Month'].dt.strftime('%B %Y')\n",
    "    for col in ['Predicted Revenue', 'Lower Bound (95%)', 'Upper Bound (95%)']:\n",
    "        forecast_table[col] = forecast_table[col].apply(lambda x: f\"R$ {x:,.0f}\")\n",
    "    st.dataframe(forecast_table, use_container_width=True, hide_index=True)\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "# PAGE 3 — EDA TRENDS\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "elif page == \"🔍 EDA — Trends\":\n",
    "    st.title(\"🔍 Revenue Trends Analysis\")\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    # Yearly\n",
    "    yearly = (\n",
    "        delivered.groupby('order_year')\n",
    "        .agg(total_revenue=('item_revenue', 'sum'), total_orders=('order_id', 'nunique'))\n",
    "        .reset_index()\n",
    "    )\n",
    "    yearly['yoy_growth'] = yearly['total_revenue'].pct_change() * 100\n",
    "\n",
    "    col1, col2 = st.columns(2)\n",
    "    with col1:\n",
    "        st.subheader(\"📊 Revenue by Year\")\n",
    "        fig = px.bar(yearly, x='order_year', y='total_revenue',\n",
    "                     text=yearly['total_revenue'].apply(lambda x: f\"R${x/1e6:.1f}M\"),\n",
    "                     color_discrete_sequence=['#2E75B6'])\n",
    "        fig.update_layout(height=350, yaxis_tickformat='R$,.0f', xaxis_title=\"Year\",\n",
    "                          yaxis_title=\"Revenue (R$)\")\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    with col2:\n",
    "        st.subheader(\"📈 Year-over-Year Growth %\")\n",
    "        yoy = yearly.dropna(subset=['yoy_growth'])\n",
    "        colors = ['#16A34A' if v >= 0 else '#DC2626' for v in yoy['yoy_growth']]\n",
    "        fig2 = go.Figure(go.Bar(x=yoy['order_year'].astype(str), y=yoy['yoy_growth'],\n",
    "                                 marker_color=colors,\n",
    "                                 text=yoy['yoy_growth'].apply(lambda x: f\"{x:.1f}%\"),\n",
    "                                 textposition='outside'))\n",
    "        fig2.update_layout(height=350, xaxis_title=\"Year\", yaxis_title=\"Growth %\")\n",
    "        st.plotly_chart(fig2, use_container_width=True)\n",
    "\n",
    "    # Monthly seasonality\n",
    "    st.subheader(\"🌊 Monthly Seasonality Pattern\")\n",
    "    month_names = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']\n",
    "    monthly_avg = delivered.groupby('order_month')['item_revenue'].mean().reset_index()\n",
    "    monthly_avg['month_name'] = monthly_avg['order_month'].apply(lambda x: month_names[x-1])\n",
    "\n",
    "    fig3 = px.bar(monthly_avg, x='month_name', y='item_revenue',\n",
    "                  color='item_revenue', color_continuous_scale='Blues',\n",
    "                  labels={'item_revenue': 'Avg Revenue (R$)', 'month_name': 'Month'})\n",
    "    fig3.update_layout(height=350, coloraxis_showscale=False)\n",
    "    st.plotly_chart(fig3, use_container_width=True)\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "# PAGE 4 — EDA CATEGORIES\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "elif page == \"🏷️ EDA — Categories\":\n",
    "    st.title(\"🏷️ Product Category Analysis\")\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    cat_rev = (\n",
    "        delivered.groupby('product_category_name')\n",
    "        .agg(total_revenue=('item_revenue', 'sum'),\n",
    "             total_orders=('order_id', 'nunique'),\n",
    "             avg_price=('price', 'mean'))\n",
    "        .reset_index()\n",
    "        .sort_values('total_revenue', ascending=False)\n",
    "        .head(10)\n",
    "    )\n",
    "\n",
    "    col1, col2 = st.columns(2)\n",
    "    with col1:\n",
    "        st.subheader(\"💰 Top 10 by Revenue\")\n",
    "        fig = px.bar(cat_rev, x='total_revenue', y='product_category_name',\n",
    "                     orientation='h', color_discrete_sequence=['#2E75B6'])\n",
    "        fig.update_layout(height=400, xaxis_tickformat='R$,.0f',\n",
    "                          yaxis={'categoryorder': 'total ascending'},\n",
    "                          yaxis_title=\"\", xaxis_title=\"Revenue (R$)\")\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    with col2:\n",
    "        st.subheader(\"📦 Top 10 by Orders\")\n",
    "        fig2 = px.bar(cat_rev, x='total_orders', y='product_category_name',\n",
    "                      orientation='h', color_discrete_sequence=['#16A34A'])\n",
    "        fig2.update_layout(height=400, yaxis={'categoryorder': 'total ascending'},\n",
    "                           yaxis_title=\"\", xaxis_title=\"Total Orders\")\n",
    "        st.plotly_chart(fig2, use_container_width=True)\n",
    "\n",
    "    st.subheader(\"📋 Category Summary Table\")\n",
    "    cat_display = cat_rev.copy()\n",
    "    cat_display['total_revenue'] = cat_display['total_revenue'].apply(lambda x: f\"R${x:,.0f}\")\n",
    "    cat_display['avg_price'] = cat_display['avg_price'].apply(lambda x: f\"R${x:,.2f}\")\n",
    "    cat_display.columns = ['Category', 'Total Revenue', 'Total Orders', 'Avg Price']\n",
    "    st.dataframe(cat_display, use_container_width=True, hide_index=True)\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "# PAGE 5 — EDA GEOGRAPHY\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "elif page == \"🗺️ EDA — Geography\":\n",
    "    st.title(\"🗺️ Geographic & Payment Analysis\")\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    state_rev = (\n",
    "        delivered.groupby('customer_state')\n",
    "        .agg(total_revenue=('item_revenue', 'sum'),\n",
    "             total_orders=('order_id', 'nunique'),\n",
    "             total_customers=('customer_id', 'nunique'))\n",
    "        .reset_index()\n",
    "        .sort_values('total_revenue', ascending=False)\n",
    "        .head(10)\n",
    "    )\n",
    "\n",
    "    col1, col2 = st.columns(2)\n",
    "    with col1:\n",
    "        st.subheader(\"🏛️ Top 10 States by Revenue\")\n",
    "        fig = px.bar(state_rev, x='total_revenue', y='customer_state',\n",
    "                     orientation='h', color_discrete_sequence=['#2E75B6'])\n",
    "        fig.update_layout(height=400, xaxis_tickformat='R$,.0f',\n",
    "                          yaxis={'categoryorder': 'total ascending'},\n",
    "                          yaxis_title=\"State\", xaxis_title=\"Revenue (R$)\")\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    with col2:\n",
    "        st.subheader(\"💳 Payment Type Distribution\")\n",
    "        pay_dist = master['payment_type'].value_counts()\n",
    "        fig2 = px.pie(values=pay_dist.values, names=pay_dist.index,\n",
    "                      color_discrete_sequence=px.colors.qualitative.Set2,\n",
    "                      hole=0.35)\n",
    "        fig2.update_layout(height=400)\n",
    "        st.plotly_chart(fig2, use_container_width=True)\n",
    "\n",
    "    if 'region' in master.columns:\n",
    "        st.subheader(\"🌎 Revenue by Region\")\n",
    "        region_rev = (\n",
    "            delivered.groupby('region')['item_revenue']\n",
    "            .sum().reset_index().sort_values('item_revenue', ascending=False)\n",
    "        )\n",
    "        fig3 = px.bar(region_rev, x='region', y='item_revenue',\n",
    "                      color='item_revenue', color_continuous_scale='Blues',\n",
    "                      labels={'item_revenue': 'Revenue (R$)', 'region': 'Region'})\n",
    "        fig3.update_layout(height=350, coloraxis_showscale=False, yaxis_tickformat='R$,.0f')\n",
    "        st.plotly_chart(fig3, use_container_width=True)\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "# PAGE 6 — EDA DELIVERY\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "elif page == \"🚚 EDA — Delivery\":\n",
    "    st.title(\"🚚 Delivery Performance Analysis\")\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    col1, col2, col3, col4 = st.columns(4)\n",
    "    with col1:\n",
    "        st.metric(\"Avg Delivery Days\", f\"{delivered['delivery_days'].mean():.1f}\")\n",
    "    with col2:\n",
    "        st.metric(\"On-Time Rate\", f\"{delivered['on_time_delivery'].mean()*100:.1f}%\")\n",
    "    with col3:\n",
    "        st.metric(\"Min Delivery\", f\"{delivered['delivery_days'].min():.0f} days\")\n",
    "    with col4:\n",
    "        st.metric(\"Max Delivery\", f\"{delivered['delivery_days'].max():.0f} days\")\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "    col1, col2 = st.columns(2)\n",
    "\n",
    "    with col1:\n",
    "        st.subheader(\"📊 Delivery Days Distribution\")\n",
    "        fig = px.histogram(\n",
    "            delivered.dropna(subset=['delivery_days']),\n",
    "            x='delivery_days', nbins=40,\n",
    "            color_discrete_sequence=['#2E75B6'],\n",
    "            labels={'delivery_days': 'Delivery Days', 'count': 'Orders'}\n",
    "        )\n",
    "        fig.add_vline(x=delivered['delivery_days'].mean(), line_dash=\"dash\", line_color=\"red\",\n",
    "                      annotation_text=f\"Mean: {delivered['delivery_days'].mean():.1f}d\")\n",
    "        fig.update_layout(height=350)\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    with col2:\n",
    "        st.subheader(\"🐌 Slowest States (Avg Delivery)\")\n",
    "        slow_states = (\n",
    "            delivered.groupby('customer_state')['delivery_days']\n",
    "            .mean().sort_values(ascending=False).head(10).reset_index()\n",
    "        )\n",
    "        fig2 = px.bar(slow_states, x='delivery_days', y='customer_state',\n",
    "                      orientation='h', color_discrete_sequence=['#F59E0B'])\n",
    "        fig2.update_layout(height=350, yaxis={'categoryorder': 'total ascending'},\n",
    "                           yaxis_title=\"State\", xaxis_title=\"Avg Days\")\n",
    "        st.plotly_chart(fig2, use_container_width=True)\n",
    "\n",
    "\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "# PAGE 7 — MODEL METRICS\n",
    "# ══════════════════════════════════════════════════════════════════\n",
    "elif page == \"🤖 Model Metrics\":\n",
    "    st.title(\"🤖 Model Performance — Facebook Prophet\")\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    # Metric cards\n",
    "    col1, col2, col3, col4, col5 = st.columns(5)\n",
    "    m = metrics.iloc[0]\n",
    "    with col1:\n",
    "        st.metric(\"MAE\", f\"R${m['MAE']:,.0f}\")\n",
    "    with col2:\n",
    "        st.metric(\"RMSE\", f\"R${m['RMSE']:,.0f}\")\n",
    "    with col3:\n",
    "        st.metric(\"R² Score\", f\"{m['R2']:.4f}\")\n",
    "    with col4:\n",
    "        st.metric(\"MAPE\", f\"{m['MAPE_pct']:.2f}%\")\n",
    "    with col5:\n",
    "        st.metric(\"Accuracy\", f\"{m['Accuracy']:.2f}%\")\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    # Actual vs Predicted\n",
    "    st.subheader(\"📊 Actual vs Predicted — Test Set\")\n",
    "    fig = go.Figure()\n",
    "    fig.add_trace(go.Scatter(\n",
    "        x=evaluation['ds'], y=evaluation['actual'],\n",
    "        name='Actual', line=dict(color='#2E75B6', width=2),\n",
    "        mode='lines+markers', marker=dict(size=7)\n",
    "    ))\n",
    "    fig.add_trace(go.Scatter(\n",
    "        x=evaluation['ds'], y=evaluation['predicted'],\n",
    "        name='Predicted', line=dict(color='#DC2626', width=2, dash='dash'),\n",
    "        mode='lines+markers', marker=dict(size=7, symbol='square')\n",
    "    ))\n",
    "    fig.update_layout(\n",
    "        height=400, xaxis_title=\"Month\", yaxis_title=\"Revenue (R$)\",\n",
    "        yaxis_tickformat='R$,.0f', hovermode='x unified',\n",
    "        title=f\"Test Set Evaluation | MAPE: {m['MAPE_pct']:.2f}% | R²: {m['R2']:.4f}\"\n",
    "    )\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    # Error chart\n",
    "    st.subheader(\"📉 Prediction Error by Month\")\n",
    "    fig2 = px.bar(evaluation,\n",
    "                  x=pd.to_datetime(evaluation['ds']).dt.strftime('%b %Y'),\n",
    "                  y='error_pct',\n",
    "                  color='error_pct',\n",
    "                  color_continuous_scale='RdYlGn_r',\n",
    "                  labels={'error_pct': 'Error %', 'x': 'Month'})\n",
    "    fig2.add_hline(y=0, line_dash=\"solid\", line_color=\"black\", line_width=1)\n",
    "    fig2.update_layout(height=350, coloraxis_showscale=False)\n",
    "    st.plotly_chart(fig2, use_container_width=True)\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "    st.info(\"\"\"\n",
    "    **Model Configuration:**\n",
    "    - Algorithm: Facebook Prophet\n",
    "    - Seasonality: Multiplicative (scales with revenue level)\n",
    "    - Changepoint prior scale: 0.1 (conservative, prevents overfitting)\n",
    "    - Holiday calendar: Brazilian national holidays\n",
    "    - Confidence interval: 95%\n",
    "    - Training data: Full dataset (2016–Feb 2026)\n",
    "    - Test set: Last 12 months of dataset\n",
    "    \"\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c8815deb-d3e5-42f5-8608-b62ff07f1f32",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
